%% Load data
load("w_perc.mat");
w_perc = struct("vs",[],"ts",[],"LOSs",[],"ku",[]);
w_perc.vs = post_data.vs;
w_perc.ts = post_data.ts;
w_perc.LOSs = post_data.LOSs;
w_perc.ku = post_data.ku;
load("wout_perc.mat");
wout_perc = struct("vs",[],"ts",[],"LOSs",[],"ku",[]);
wout_perc.vs = post_data.vs;
wout_perc.ts = post_data.ts;
wout_perc.LOSs = post_data.LOSs;
wout_perc.ku = post_data.ku;
load("min_time.mat");
mintime = struct("vs",[],"ts",[],"LOSs",[],"ku",[]);
mintime.vs = post_data.vs;
mintime.ts = post_data.ts;
mintime.LOSs = post_data.LOSs;
mintime.ku = post_data.ku;
%% Plot data
close all;
orange = [0.8500 0.3250 0.0980];
blue = [0 0.4470 0.7410];
purple = [0.4940 0.1840 0.5560];
figure(1);
subplot(2,1,1);
hold on;
plot(mintime.ts,mintime.vs,"Color",purple,"DisplayName","Minimum Travel Time","LineWidth",2);
plot(w_perc.ts,w_perc.vs,"Color",blue,"DisplayName","With Safety, With Perception","LineWidth",2);
plot(wout_perc.ts,wout_perc.vs,"Color",orange,"DisplayName","With Safety, Without Pereption","LineWidth",2);
ylabel("Velocity (m/s)");
legend('Location','east');
set(gca,"FontSize",15);
grid on;
xlim([0.5 6.5]);
subplot(2,1,2);
hold on;
% yyaxis left;
% plot(mintime.ts,mintime.LOSs+0.5,"-","Color",blue,"DisplayName","Minimum Travel Time","LineWidth",2);
% plot(w_perc.ts,w_perc.LOSs+0.5,"--","Color",blue,"DisplayName","With Perception","LineWidth",2);
% plot(wout_perc.ts,wout_perc.LOSs+0.5,"-.","Color",blue,"DisplayName","Wout Perception","LineWidth",2);
% yyaxis right;
plot(mintime.ts,mintime.ku.areas,"-","Color",purple,"DisplayName","Minimum Travel Time","LineWidth",2);
plot(w_perc.ts,w_perc.ku.areas,"-","Color",blue,"DisplayName","With Perception","LineWidth",2);
plot(wout_perc.ts,wout_perc.ku.areas,"-","Color",orange,"DisplayName","Wout Perception","LineWidth",2);
ylabel("A_{ku} (m^2)");
% legend('Location','eastoutside');
xlabel("Time (s)");
grid on;
xlim([0.1 6.5]);
set(gca,"FontSize",15);
% sgtitle("Comparing With(out) Perception");