%% Load data
load("w_perc.mat");
w_perc = struct("vs",[],"ts",[],"LOSs",[],"ku",[]);
w_perc.vs = post_data.vs;
w_perc.ts = post_data.ts;
w_perc.LOSs = post_data.LOSs;
w_perc.ku = post_data.ku;
load("wout_perc.mat");
wout_perc = struct("vs",[],"ts",[],"LOSs",[],"ku",[]);
wout_perc.vs = post_data.vs;
wout_perc.ts = post_data.ts;
wout_perc.LOSs = post_data.LOSs;
wout_perc.ku = post_data.ku;
%% Plot data
close all;
orange = [0.8500 0.3250 0.0980];
blue = [0 0.4470 0.7410];
figure(1);
subplot(2,1,1);
hold on;
plot(w_perc.ts,w_perc.vs,"Color",blue,"DisplayName","With Perception","LineWidth",2);
plot(wout_perc.ts,wout_perc.vs,"Color",orange,"DisplayName","Wout Pereption","LineWidth",2);
ylabel("Velocity (m/s)");
legend('Location','eastoutside');
grid on;
subplot(2,1,2);
hold on;
yyaxis left;
plot(w_perc.ts,w_perc.LOSs,"-","Color",blue,"DisplayName","With Perception","LineWidth",2);
plot(wout_perc.ts,wout_perc.LOSs,"--","Color",blue,"DisplayName","Wout Perception","LineWidth",2);
ylabel("LOS (m)");
yyaxis right;
plot(w_perc.ts,w_perc.ku,"-","Color",orange,"DisplayName","With Perception","LineWidth",2);
plot(wout_perc.ts,wout_perc.ku,"--","Color",orange,"DisplayName","Wout Perception","LineWidth",2);
ylabel("Known Unknown (m^2)");
legend('Location','eastoutside');
xlabel("Time (s)");
grid on;
sgtitle("Comparing With(out) Perception");