load("ppl_w_perc.mat");
close all;
ppl_w_perc = ppl;
load("ppl_wout_perc.mat");
close all;
ppl_wout_perc = ppl;
load("ppl_wout_safety_wout_perc.mat");
close all;
ppl_wout_safety_wout_perc = ppl;
figure(1);
hold on;
min_r = min([ppl_w_perc.data.rs;ppl_wout_perc.data.rs;ppl_wout_safety_wout_perc.data.rs]);
max_r = max([ppl_w_perc.data.rs;ppl_wout_perc.data.rs;ppl_wout_safety_wout_perc.data.rs]);
edges = min_r:0.2:1.01*max_r;
histogram(ppl_wout_safety_wout_perc.data.rs,edges,"Normalization","cdf","DisplayName","Minimize Traveling Time");
histogram(ppl_wout_perc.data.rs,edges,"Normalization","cdf","DisplayName","With Safety, Without Perception");
histogram(ppl_w_perc.data.rs,edges,"Normalization","cdf","DisplayName","With Safety, With Perception");
grid on;
xlabel("Distance of First Sight (m)");
ylabel("CDF");
title("Without Perception");
legend("Location","northwest");
% figure(2);
% histogram(ppl_w_perc.data.rs,"Normalization","cdf");
% xlabel("Distance of First Sight");
% ylabel("CDF");
title("With Perception");